name: stackfg_env
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python==3.12.12
  - pandas
  - numpy
  - scikit-learn
  - joblib
  - xgboost
  - tensorflow
  - pip
  - star-fusion
